### ISSUE TITLE
Erreur au déploiement de ginco-admin.war

### ISSUE THREAD

**Issue by ndelaforge** [culturecommunication/ginco#22]
Bonjour,

J'essaye de déployer GINCO sur un serveur ubuntu avec tomcat 7.
J'ai réussi à faire la majeure partie de l'installation, le war ginco-webservices s'est bien installé, par contre le ginco-admin me sort des exceptions Spring.

Voici mon ginco.log

```
2015-02-27 12:28:50,766 ERROR | localhost-startStop-1 | org.springframework.web.context.ContextLoader           | Context initialization failed
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://cxf.apache.org/jaxws]
Offending resource: file [/var/cache/tomcat7/Catalina/localhost/ginco-admin/WEB-INF/classes/spring/applicationContext-soap.xml]

	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:80) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.error(BeanDefinitionParserDelegate.java:317) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1432) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1425) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:184) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:140) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:111) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:537) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:670) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839) [tomcat-catalina-7.0.52.jar:7.0.52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
2015-02-27 12:28:50,795  WARN | localhost-startStop-1 | o.s.web.context.support.XmlWebApplicationContext        | Exception thrown from ApplicationListener handling ContextClosedEvent
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: Root WebApplicationContext: startup date [Fri Feb 27 12:28:49 CET 2015]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:347) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1049) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:549) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5014) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5659) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:670) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839) [tomcat-catalina-7.0.52.jar:7.0.52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
2015-02-27 12:28:50,796  WARN | localhost-startStop-1 | o.s.web.context.support.XmlWebApplicationContext        | Exception thrown from LifecycleProcessor on context close
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: Root WebApplicationContext: startup date [Fri Feb 27 12:28:49 CET 2015]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:360) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1057) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:549) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5014) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5659) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:670) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839) [tomcat-catalina-7.0.52.jar:7.0.52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
```

**Comment by fredericrolland** [comment]
Bonjour,
j'ai transmis le bug à mon prestataire pour expertise. Je n'ai pas de 
réponse. Pourriez-vous poster votre problème sur Github ?
merci d'avance,
cordialement,
fr
Le 27/02/2015 12:44, Nicolas Delaforge a écrit :
>
> Bonjour,
>
> J'essaye de déployer GINCO sur un serveur ubuntu avec tomcat 7.
> J'ai réussi à faire la majeure partie de l'installation, le war 
> ginco-webservices s'est bien installé, par contre le ginco-admin me 
> sort des exceptions Spring.
>
> Voici mon ginco.log
>
> |2015-02-27 12:28:50,766 ERROR | localhost-startStop-1 | org.springframework.web.context.ContextLoader           | Context initialization failed
> org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://cxf.apache.org/jaxws]
> Offending resource: file [/var/cache/tomcat7/Catalina/localhost/ginco-admin/WEB-INF/classes/spring/applicationContext-soap.xml]
>
>      at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:80) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.error(BeanDefinitionParserDelegate.java:317) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1432) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1425) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:184) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:140) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:111) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180) ~[spring-beans-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:537) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283) ~[spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:670) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
>      at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
>      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
>      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
>      at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
> 2015-02-27 12:28:50,795  WARN | localhost-startStop-1 | o.s.web.context.support.XmlWebApplicationContext        | Exception thrown from ApplicationListener handling ContextClosedEvent
> java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: Root WebApplicationContext: startup date [Fri Feb 27 12:28:49 CET 2015]; root of context hierarchy
>      at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:347) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1049) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:549) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5014) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5659) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:670) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
>      at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
>      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
>      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
>      at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
> 2015-02-27 12:28:50,796  WARN | localhost-startStop-1 | o.s.web.context.support.XmlWebApplicationContext        | Exception thrown from LifecycleProcessor on context close
> java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: Root WebApplicationContext: startup date [Fri Feb 27 12:28:49 CET 2015]; root of context hierarchy
>      at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:360) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1057) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:549) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [spring-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
>      at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5014) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5659) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:670) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839) [tomcat-catalina-7.0.52.jar:7.0.52]
>      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
>      at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
>      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
>      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
>      at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/culturecommunication/ginco/issues/22>.
>

----------------------------------------------------------------------
Merci de nous aider à préserver l'environnement en n'imprimant ce courriel et les documents joints que si nécessaire.

**Comment by ndelaforge** [comment]
Il me semblait que j'étais déjà sur Github. :)

**Comment by hufon** [comment]
Bonjour,

La plateforme supportée est Centos avec Tomcat6.

Utilisez vous le tomcat 7 livré par ubuntu. Quelle est votre version d'ubuntu?

**Comment by ndelaforge** [comment]
Je suis sur un serveur Ubuntu 14.04.1 LTS (Codename : trusty)
Le Tomcat utilisé est effectivement celui fourni par Ubuntu. (package version: 7.0.52-1ubuntu0.1)
Pour le JDK : 
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

**Comment by hufon** [comment]
Je vous recommande fortement d'essayer avec un tomcat 6 téléchargé directement depuis le site d'apache...
