### ISSUE TITLE
ginco-cli : Error creating bean with name 'sessionInitier'

### ISSUE THREAD

**Issue by jajm** [culturecommunication/ginco#58]
Bonjour,

j'essaie d'utiliser ginco-cli pour faire un export SKOS, mais je n'arrive pas à le faire fonctionner.

Premier essai:

```sh
java -jar ginco-cli/target/ginco-cli-2.0.9-SNAPSHOT.jar -e tess:TESS output
```

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ginco/ginco/ginco-cli/target/lib/logback-classic-1.0.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ginco/ginco/ginco-cli/target/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2017-09-15 13:19:18,837  INFO | main | o.s.context.support.ClassPathXmlApplicationContext      | Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@887af79: startup date [Fri Sep 15 13:19:18 CEST 2017]; root of context hierarchy 
2017-09-15 13:19:18,864  INFO | main | o.s.beans.factory.xml.XmlBeanDefinitionReader           | Loading XML bean definitions from class path resource [applicationContext-cli.xml] 
2017-09-15 13:19:19,103  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [hibernate.properties] 
2017-09-15 13:19:19,104  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [hibernate.properties]: class path resource [hibernate.properties] cannot be opened because it does not exist 
2017-09-15 13:19:19,104  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [application.properties] 
2017-09-15 13:19:19,104  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [application.properties]: class path resource [application.properties] cannot be opened because it does not exist 
2017-09-15 13:19:19,104  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [git.properties] 
2017-09-15 13:19:19,104  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [git.properties]: class path resource [git.properties] cannot be opened because it does not exist 
2017-09-15 13:19:19,104  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [labels.properties] 
2017-09-15 13:19:19,104  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [labels.properties]: class path resource [labels.properties] cannot be opened because it does not exist 
2017-09-15 13:19:19,104  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [db.properties] 
2017-09-15 13:19:19,105  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from URL [file:ginco-cli.properties] 
2017-09-15 13:19:19,105  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from URL [file:ginco-cli.properties]: ginco-cli.properties (No such file or directory) 
2017-09-15 13:19:19,107  WARN | main | o.s.context.support.ClassPathXmlApplicationContext      | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'solrServer' defined in class path resource [applicationContext-cli.xml]: Could not resolve placeholder 'solr.url' in string value "${solr.url}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'solr.url' in string value "${solr.url}" 
2017-09-15 13:19:19,107  INFO | main | o.s.beans.factory.support.DefaultListableBeanFactory    | Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@40a4337a: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,sessionInitier,cliExporter,cliImporter,dataSource,solrServer,propertyConfigurer,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy 
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'solrServer' defined in class path resource [applicationContext-cli.xml]: Could not resolve placeholder 'solr.url' in string value "${solr.url}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'solr.url' in string value "${solr.url}"
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:209)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:222)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:84)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:699)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:674)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at fr.mcc.ginco.cli.App.main(App.java:66)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'solr.url' in string value "${solr.url}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:173)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:125)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer$PlaceholderResolvingStringValueResolver.resolveStringValue(PropertyPlaceholderConfigurer.java:257)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:204)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitIndexedArgumentValues(BeanDefinitionVisitor.java:150)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:84)
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:206)
	... 8 more
```

Il n'arrive visiblement pas à charger les fichiers de conf.

Pour essayer de contourner le problème je crée un fichier ginco-cli.properties contenant

```
solr.url=http://localhost:8983/solr/thesaurus/
```

et je relance

```sh
java -jar ginco-cli/target/ginco-cli-2.0.9-SNAPSHOT.jar -e tess:TESS output
```

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ginco/ginco/ginco-cli/target/lib/logback-classic-1.0.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ginco/ginco/ginco-cli/target/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2017-09-15 13:23:03,486  INFO | main | o.s.context.support.ClassPathXmlApplicationContext      | Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@887af79: startup date [Fri Sep 15 13:23:03 CEST 2017]; root of context hierarchy 
2017-09-15 13:23:03,512  INFO | main | o.s.beans.factory.xml.XmlBeanDefinitionReader           | Loading XML bean definitions from class path resource [applicationContext-cli.xml] 
2017-09-15 13:23:03,748  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [hibernate.properties] 
2017-09-15 13:23:03,748  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [hibernate.properties]: class path resource [hibernate.properties] cannot be opened because it does not exist 
2017-09-15 13:23:03,748  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [application.properties] 
2017-09-15 13:23:03,748  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [application.properties]: class path resource [application.properties] cannot be opened because it does not exist 
2017-09-15 13:23:03,748  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [git.properties] 
2017-09-15 13:23:03,748  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [git.properties]: class path resource [git.properties] cannot be opened because it does not exist 
2017-09-15 13:23:03,748  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [labels.properties] 
2017-09-15 13:23:03,748  WARN | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Could not load properties from class path resource [labels.properties]: class path resource [labels.properties] cannot be opened because it does not exist 
2017-09-15 13:23:03,748  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from class path resource [db.properties] 
2017-09-15 13:23:03,749  INFO | main | o.s.beans.factory.config.PropertyPlaceholderConfigurer  | Loading properties file from URL [file:ginco-cli.properties] 
2017-09-15 13:23:03,751  INFO | main | o.s.b.f.annotation.AutowiredAnnotationBeanPostProcessor | JSR-330 'javax.inject.Inject' annotation found and supported for autowiring 
2017-09-15 13:23:03,757  INFO | main | o.s.beans.factory.support.DefaultListableBeanFactory    | Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@40a4337a: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,sessionInitier,cliExporter,cliImporter,dataSource,solrServer,propertyConfigurer,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy 
2017-09-15 13:23:03,767  WARN | main | o.s.context.support.ClassPathXmlApplicationContext      | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionInitier': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.hibernate.SessionFactory fr.mcc.ginco.cli.SessionInitier.sessionFactory; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.hibernate.SessionFactory] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject(), @javax.inject.Named(value=gincoSessionFactory)} 
2017-09-15 13:23:03,767  INFO | main | o.s.beans.factory.support.DefaultListableBeanFactory    | Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@40a4337a: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,sessionInitier,cliExporter,cliImporter,dataSource,solrServer,propertyConfigurer,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy 
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionInitier': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.hibernate.SessionFactory fr.mcc.ginco.cli.SessionInitier.sessionFactory; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.hibernate.SessionFactory] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject(), @javax.inject.Named(value=gincoSessionFactory)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:298)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1148)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at fr.mcc.ginco.cli.App.main(App.java:66)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.hibernate.SessionFactory fr.mcc.ginco.cli.SessionInitier.sessionFactory; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.hibernate.SessionFactory] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject(), @javax.inject.Named(value=gincoSessionFactory)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:531)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:295)
	... 13 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.hibernate.SessionFactory] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject(), @javax.inject.Named(value=gincoSessionFactory)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:997)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:867)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:779)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:503)
	... 15 more
```

Là je bloque... Une idée ?

```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

$ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-3-amd64", arch: "amd64", family: "unix"
```

**Comment by fredericrolland** [comment]
Bonjour,
lisez la notice que je viens de créer dans  ginco/doc/CLI-README.md
Cordialement,
fr

**Comment by jajm** [comment]
Bonjour,

j'ai réessayé en suivant les instructions de [CLI-README.md](https://github.com/culturecommunication/ginco/blob/master/doc/CLI-README.md) et j'ai toujours la même erreur (https://gist.github.com/jajm/802ac94ebd734383117963dc4af51693)

Mon ginco-cli.properties:

```
solr.url=http://localhost:8983/solr/thesaurus/
jdbc.url=jdbc:postgresql://localhost:5432/ginco?useUnicode=true&amp;characterEncoding=UTF-8&amp;useFastDateParsing=false
jdbc.username=ginco
jdbc.password=ginco
```

**Comment by fredericrolland** [comment]
bonjour,
pourriez-vous tester l'url:
http://localhost:8983/solr/

**Comment by jajm** [comment]
```
$ curl 'http://localhost:8983/solr/thesaurus/select?q=*:*&wt=json'
{"responseHeader":{"status":0,"QTime":0,"params":{"q":"*:*","wt":"json"}},"response":{"numFound":2,"start":0,"docs":[{"thesaurusId":"http://data.culture.fr/thesaurus/resource/ark:/67717/717a0074-4ba2-4391-942c-e6a1725ecffd","thesaurusTitle":"Pays","identifier":"http://data.culture.fr/thesaurus/resource/ark:/67717/f063842b-503c-421f-8397-ce9ba08c027d","lexicalValue":"France","type":"ThesaurusTerm","language":["fr-FR"],"conceptId":"http://data.culture.fr/thesaurus/resource/ark:/67717/36341e3b-bb55-40fc-9914-f3b1568e3923","ext_type":2,"modified":"2017-10-11T09:29:29.931Z","created":"2017-10-11T09:29:29.927Z","status":"1","_version_":1580952893747363840},{"thesaurusId":"http://data.culture.fr/thesaurus/resource/ark:/67717/717a0074-4ba2-4391-942c-e6a1725ecffd","thesaurusTitle":"Pays","identifier":"http://data.culture.fr/thesaurus/resource/ark:/67717/36341e3b-bb55-40fc-9914-f3b1568e3923","type":"ThesaurusConcept","ext_type":1,"modified":"2017-10-11T09:29:29.921Z","created":"2017-10-11T09:29:29.92Z","status":"1","language":["fr-FR"],"lexicalValue":"France","_version_":1580952893747363841}]}}
```

**Comment by fredericrolland** [comment]
et avec http://localhost:8983/solr/

**Comment by jajm** [comment]
http://localhost:8983/solr/ est l'adresse de l'interface d'admin. Elle fonctionne.
Je lance la commande comme ceci:

    java -jar ginco-cli-2.0.9-SNAPSHOT.jar -e http://data.culture.fr/thesaurus/resource/ark:/67717/36341e3b-bb55-40fc-9914-f3b1568e3923 test.rdf >log 2>&1

**Comment by fredericrolland** [comment]
nous avons constaté une erreur également chez nous. Nous explorons le problème et revenons vers vous dès que possible.
Cordialement

**Comment by fredericrolland** [comment]
Bonjour,
lancez-vous la commande depuis le répertoire 
ginco/ginco-cli/target ?
si oui, avez-vous un répertoire lib présent dans ce répertoire ?
si oui, pouvez-vous me fournir la liste des librairies présentes dans ce répertoire ?
Merci
Cordialement,
fr

**Comment by jajm** [comment]
Bonjour,
voici la liste des fichiers présents dans ginco-cli/target/lib

```
antlr-2.7.7.jar
aopalliance-1.0.jar
apache-jena-libs-2.10.0.pom
aspectjrt-1.7.1.jar
aspectjweaver-1.7.1.jar
classworlds-1.1-alpha-2.jar
commons-cli-1.2.jar
commons-codec-1.6.jar
commons-collections-3.2.1.jar
commons-io-2.1.jar
commons-lang3-3.1.jar
cxf-common-utilities-2.5.9.jar
dbcp-6.0.29.jar
dom4j-1.6.1.jar
ginco-api.jar
ginco-commons.jar
ginco-impl.jar
hibernate-commons-annotations-4.0.1.Final.jar
hibernate-core-4.1.10.Final.jar
hibernate-entitymanager-4.1.10.Final.jar
hibernate-envers-4.1.10.Final.jar
hibernate-jpa-2.0-api-1.0.1.Final.jar
httpclient-4.2.3.jar
httpcore-4.2.2.jar
httpmime-4.2.3.jar
jackson-core-asl-1.9.11.jar
javassist-3.15.0-GA.jar
javax.inject-1.jar
jboss-logging-3.1.0.GA.jar
jboss-transaction-api_1.1_spec-1.0.0.Final.jar
jcl-over-slf4j-1.6.6.jar
jena-arq-2.10.0.jar
jena-core-2.10.0.jar
jena-iri-0.9.5.jar
jena-tdb-0.10.0.jar
junit-3.8.1.jar
log4j-1.2.16.jar
logback-classic-1.0.9.jar
logback-core-1.0.9.jar
maven-artifact-2.0.6.jar
maven-artifact-manager-2.0.6.jar
maven-model-2.0.6.jar
maven-plugin-api-2.0.6.jar
maven-plugin-registry-2.0.6.jar
maven-profile-2.0.6.jar
maven-project-2.0.6.jar
maven-repository-metadata-2.0.6.jar
maven-settings-2.0.6.jar
plexus-container-default-1.0-alpha-9-stable-1.jar
plexus-utils-1.5.6.jar
postgresql-9.1-901.jdbc4.jar
properties-maven-plugin-1.0-alpha-2.jar
slf4j-api-1.6.6.jar
slf4j-log4j12-1.6.4.jar
solr-solrj-4.2.0.jar
spring-aop-3.2.16.RELEASE.jar
spring-beans-3.2.16.RELEASE.jar
spring-context-3.2.16.RELEASE.jar
spring-core-3.2.16.RELEASE.jar
spring-expression-3.2.16.RELEASE.jar
spring-jdbc-3.2.16.RELEASE.jar
spring-orm-3.2.16.RELEASE.jar
spring-security-config-3.1.3.RELEASE.jar
spring-security-core-3.1.3.RELEASE.jar
spring-test-3.2.16.RELEASE.jar
spring-tx-3.2.16.RELEASE.jar
spring-web-3.2.16.RELEASE.jar
stax2-api-3.1.1.jar
wagon-provider-api-1.0-beta-2.jar
woodstox-core-asl-4.1.4.jar
wstx-asl-3.2.7.jar
xercesImpl-2.10.0.jar
xml-apis-1.4.01.jar
xmlschema-core-2.0.3.jar
zookeeper-3.4.5.jar
```

**Comment by fredericrolland** [comment]
l'export fonctionne chez nous. Il faut exécuter la commande dans le répertoire target.

**Comment by jajm** [comment]
L'erreur est la même, que je sois dans le répertoire target ou non.
